name: colegio_app
description: Aplicación móvil para gestión de colegio
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  intl: ^0.19.0
  provider: ^6.1.1
  file_picker: ^8.1.4
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  open_filex: ^4.7.0
  webview_flutter: ^4.4.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/alfabeto.png
  android: true
  ios: false
  web: false
  android_gravity: fill
  fullscreen: true
  android_12:
    image: assets/images/alfabeto.png
    color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/alfabeto.png"
  min_sdk_android: 21
